"""initial

Revision ID: 311b01321694
Revises: 
Create Date: 2026-04-15 18:59:13.837978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '311b01321694'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sources_count', sa.Integer(), nullable=False),
    sa.Column('data_period_months', sa.Integer(), nullable=False),
    sa.Column('avg_monthly_income_kgs', sa.Float(), nullable=False),
    sa.Column('income_stability_score', sa.Float(), nullable=False),
    sa.Column('income_trend', sa.Float(), nullable=False),
    sa.Column('income_by_source', sa.Text(), nullable=True),
    sa.Column('income_by_category', sa.Text(), nullable=True),
    sa.Column('defter_score', sa.Integer(), nullable=True),
    sa.Column('recommended_limit', sa.Float(), nullable=True),
    sa.Column('fraud_risk_score', sa.Integer(), nullable=True),
    sa.Column('score_components', sa.Text(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PARSING', 'AGGREGATING', 'SCORING', 'DONE', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('step', sa.String(length=50), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('files_count', sa.Integer(), nullable=False),
    sa.Column('result_profile_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['result_profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_jobs_id'), 'processing_jobs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processing_jobs_id'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###
