"""initial

Revision ID: 4fc231e0fef2
Revises: 
Create Date: 2026-04-27 11:34:51.008426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fc231e0fef2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('inn', sa.String(length=14), nullable=False),
    sa.Column('passport_id', sa.String(length=9), nullable=False),
    sa.Column('birth_date', sa.DateTime(), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('business_type', sa.String(length=50), nullable=False),
    sa.Column('occupation', sa.Enum('PATENT', 'EMPLOYED', 'SELF_EMPLOYED', 'IP', 'OTHER', name='occupationenum'), nullable=False),
    sa.Column('consent_given_at', sa.DateTime(), nullable=False),
    sa.Column('consent_version', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_inn'), 'users', ['inn'], unique=True)
    op.create_index(op.f('ix_users_passport_id'), 'users', ['passport_id'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('fraud_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('flag_type', sa.Enum('METADATA_MISMATCH', 'ROUND_AMOUNTS', 'BALANCE_MISMATCH', 'NIGHT_TRANSFERS', 'CROSS_SOURCE_DUPLICATE', 'DATE_ANOMALY', 'FREQUENCY_ANOMALY', name='fraudflagtype'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='fraudseverity'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fraud_flags_id'), 'fraud_flags', ['id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sources_count', sa.Integer(), nullable=False),
    sa.Column('data_period_months', sa.Integer(), nullable=False),
    sa.Column('avg_monthly_income_kgs', sa.Float(), nullable=False),
    sa.Column('income_stability_score', sa.Float(), nullable=False),
    sa.Column('income_trend', sa.Float(), nullable=False),
    sa.Column('income_by_source', sa.Text(), nullable=True),
    sa.Column('income_by_category', sa.Text(), nullable=True),
    sa.Column('defter_score', sa.Integer(), nullable=True),
    sa.Column('recommended_limit', sa.Float(), nullable=True),
    sa.Column('fraud_risk_score', sa.Integer(), nullable=True),
    sa.Column('score_components', sa.Text(), nullable=True),
    sa.Column('total_income', sa.Float(), nullable=True),
    sa.Column('total_expense', sa.Float(), nullable=True),
    sa.Column('avg_expense_monthly', sa.Float(), nullable=True),
    sa.Column('expense_to_income_ratio', sa.Float(), nullable=True),
    sa.Column('net_cashflow_monthly', sa.Float(), nullable=True),
    sa.Column('overdraft_count', sa.Integer(), nullable=True),
    sa.Column('max_overdraft_amount', sa.Float(), nullable=True),
    sa.Column('income_anomaly_detected', sa.Boolean(), nullable=True),
    sa.Column('ai_verdict', sa.Text(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('MBANK', 'ELSOM', 'ODENGI', 'BAKAI', 'SIMBANK', 'ELDIK', 'KOMPANYON', 'DEMIR', 'RSK', name='sourceenum'), nullable=False),
    sa.Column('txn_date', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.Enum('KGS', 'USD', 'EUR', 'TL', name='currencyenum'), nullable=False),
    sa.Column('amount_kgs', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('txn_type', sa.Enum('QR_PAYMENT', 'CARD_PAYMENT', 'TRANSFER_IN', 'TRANSFER_OUT', 'TAX', 'FEE', 'CASH', 'LOAN_REPAYMENT', 'OTHER', name='txntype'), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('recipient_phone', sa.String(length=20), nullable=True),
    sa.Column('external_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PARSING', 'AGGREGATING', 'SCORING', 'DONE', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('step', sa.String(length=50), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('files_count', sa.Integer(), nullable=False),
    sa.Column('result_profile_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['result_profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_jobs_id'), 'processing_jobs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processing_jobs_id'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_fraud_flags_id'), table_name='fraud_flags')
    op.drop_table('fraud_flags')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_passport_id'), table_name='users')
    op.drop_index(op.f('ix_users_inn'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
