"""initial

Revision ID: 6637503e2948
Revises: 
Create Date: 2026-04-15 16:25:23.630967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6637503e2948'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('inn', sa.String(length=14), nullable=False),
    sa.Column('passport_id', sa.String(length=9), nullable=False),
    sa.Column('birth_date', sa.DateTime(), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('business_type', sa.String(length=50), nullable=False),
    sa.Column('occupation', sa.Enum('PATENT', 'EMPLOYED', 'SELF_EMPLOYED', 'IP', 'OTHER', name='occupationenum'), nullable=False),
    sa.Column('consent_given_at', sa.DateTime(), nullable=False),
    sa.Column('consent_version', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_inn'), 'users', ['inn'], unique=True)
    op.create_index(op.f('ix_users_passport_id'), 'users', ['passport_id'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('fraud_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('flag_type', sa.Enum('METADATA_MISMATCH', 'ROUND_AMOUNTS', 'BALANCE_MISMATCH', 'NIGHT_TRANSFERS', 'CROSS_SOURCE_DUPLICATE', 'DATE_ANOMALY', 'FREQUENCY_ANOMALY', name='fraudflagtype'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='fraudseverity'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fraud_flags_id'), 'fraud_flags', ['id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('MBANK', 'BAKAI', 'O', 'SIMBANK', 'ELDIK', 'KOMPANYON', 'DEMIR', 'RSK', name='sourceenum'), nullable=False),
    sa.Column('txn_date', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.Enum('KGS', 'USD', 'EUR', 'TL', name='currencyenum'), nullable=False),
    sa.Column('amount_kgs', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('txn_type', sa.Enum('QR_PAYMENT', 'CARD_PAYMENT', 'TRANSFER_IN', 'TRANSFER_OUT', 'TAX', 'FEE', 'CASH', 'LOAN_REPAYMENT', 'OTHER', name='txntype'), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_fraud_flags_id'), table_name='fraud_flags')
    op.drop_table('fraud_flags')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_passport_id'), table_name='users')
    op.drop_index(op.f('ix_users_inn'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
