"""add_financial_metrics_to_profile

Revision ID: d45d2811f6ab
Revises: c8052e52761f
Create Date: 2026-04-17 12:01:59.095551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd45d2811f6ab'
down_revision: Union[str, Sequence[str], None] = 'c8052e52761f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('total_income', sa.Float(), nullable=True))
    op.add_column('profiles', sa.Column('total_expense', sa.Float(), nullable=True))
    op.add_column('profiles', sa.Column('avg_expense_monthly', sa.Float(), nullable=True))
    op.add_column('profiles', sa.Column('expense_to_income_ratio', sa.Float(), nullable=True))
    op.add_column('profiles', sa.Column('net_cashflow_monthly', sa.Float(), nullable=True))
    op.add_column('profiles', sa.Column('overdraft_count', sa.Integer(), nullable=True))
    op.add_column('profiles', sa.Column('max_overdraft_amount', sa.Float(), nullable=True))
    op.add_column('profiles', sa.Column('income_anomaly_detected', sa.Boolean(), nullable=True))
    op.add_column('profiles', sa.Column('ai_verdict', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'ai_verdict')
    op.drop_column('profiles', 'income_anomaly_detected')
    op.drop_column('profiles', 'max_overdraft_amount')
    op.drop_column('profiles', 'overdraft_count')
    op.drop_column('profiles', 'net_cashflow_monthly')
    op.drop_column('profiles', 'expense_to_income_ratio')
    op.drop_column('profiles', 'avg_expense_monthly')
    op.drop_column('profiles', 'total_expense')
    op.drop_column('profiles', 'total_income')
    # ### end Alembic commands ###
