"""initial

Revision ID: ff40b10c722b
Revises: 
Create Date: 2026-04-16 23:36:10.340947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff40b10c722b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('recipient_phone', sa.String(length=20), nullable=True))
    op.add_column('transactions', sa.Column('external_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'external_id')
    op.drop_column('transactions', 'recipient_phone')
    # ### end Alembic commands ###
